### ISSUE TITLE
'card' image for twitter/facebook broken URL

### ISSUE THREAD

**Issue by harry-wood** [zerebubuth/osm-hardware-2014#11]
The page has meta tags pointing at 'card' images for twitter/facebook, but there's no image at the specified URL http://donate.osm.org/img/twitter-card.png    (three different meta tags)

From this repo we are deploying a suitable image to the URL http://donate.openstreetmap.org/server2015/img/twitter-card.png

Three options
- Simply swap the URL  https://github.com/harry-wood/osm-hardware-2014/commit/512cc364c123984df54d46b9d46522693f1e16b9  
- Deploy the image to http://donate.osm.org/img/twitter-card.png
- Deploy to both. We could have a slightly different card image for the 2015 fundraising drive versus the generic donate site.

[Issue noticed and reported to me by !i!](http://wiki.openstreetmap.org/w/index.php?title=User_talk:Harry_Wood&diff=1189378&oldid=1180492&rcid=1330721&curid=1253)

**Comment by harry-wood** [comment]
seemed to be fixed

**Comment by zerebubuth** [comment]
Ooops, yeah. Sorry - I fixed it but forgot to say anything.
