### ISSUE TITLE
"close" the funding drive.

### ISSUE THREAD

**Issue by harry-wood** [zerebubuth/osm-hardware-2014#14]
There's various things we need to do now to "close" the funding drive. Not a glamorous job, but time to do it.

To put the donate site back to "business as usual", we need a site at donate.openstreetmap.org  But I'm not sure the best approach.  It could be a variation on this nicely designed fundraiser site, probably without any specific server details, but some generic details. Probably without any named donors list (Don't think we have that normally do we? Just during funding drives?)

Then I guess we either
A) Make donate.openstreetmap.org/server2015 redirect to donate.openstreetmap.org, and then the donor list and server details of this funding drive are no longer kept.
B) Keep donate.openstreetmap.org/server2015  but stop tracking new donors there, but keep the list. So maybe label it as "closed" and link people to donate.openstreetmap.org

Probably A is the easiest way. But people can no longer see who donated what.

**Comment by zerebubuth** [comment]
The old site at donate.openstreetmap.org still exists, it's just hidden by
a redirect at the moment. I'll fix that when I'm back.

We'll do option B, as that's how Grant has set it up already, and means the
site is kept in case anyone wants to refer to it later.

If anyone has suggestions or a PR for copy to use this design generically
then I'd be really happy to get them. The simplest thing for the moment is
just to use the existing generic page, and we can work on something better
concurrently.

**Comment by zerebubuth** [comment]
I've dropped the redirect, so the old donate "home" site is back as per usual. Let's open another issue (or, even better, a PR) for an improved "home" site.

**Comment by harry-wood** [comment]
Did you stop tracking new donors on the server2015 site too?

**Comment by zerebubuth** [comment]
If they donate on the server2015 site, they'll be tracked on that site. If they donate on the main page, they won't. I could replace the donation stuff with a link back to the main site, if we want to prevent any more donors being appended to the server2015 drive... do we want to do that?

**Comment by harry-wood** [comment]
I'm thinking...    It would be weird and over-complicated to leave that tracking running forever e.g. we wouldn't keep it there while we launch another fundraising site next year...  therefore we should shut it off and just go static at some point.... therefore we might as well make that point now, since we're declaring it "closed".

The fun dynamic code will be brought back into play next time of course. Or sooner if we were to add a 'recent donation' display on the main site.
