### ISSUE TITLE
Choose a currency and then click £50

### ISSUE THREAD

**Issue by harry-wood** [zerebubuth/osm-hardware-2014#9]
If you choose a currency in the drop-down and then click £50, then behaviour might be unexpected.   ...I mean it's not _that_ unexpected, and it's a weird thing to do but...

I guess ideally it would swap the currency symbol shown in the above selectors... although then we might want to adjust the suggested amounts too. Hmmm. I haven't thought this through

**Comment by zerebubuth** [comment]
I sort of fixed this in 17730287 I think... Now it changes the currency symbols, so it's always however many units of the current currency. But to avoid unintentional side-effects it doesn't change the number in the box. Might still be confusing, depending on the order of the clicks... but at the moment I can't think of a better way to do it.
